version: "2.3"
networks:
  sentiment_network:
    name: sentiment_network

services:
  proxy:
    networks:
      - sentiment_network
    container_name: sentiment_proxy_service
    build:
      context: ./proxy
      dockerfile: Dockerfile   
    ports:
      - "3041:3041"  
    volumes:
      - "./proxy:/app"  

  sentiment_service:
    networks:
      - sentiment_network
    container_name: sentiment_service
    build:
      context: ./sentiment
      dockerfile: Dockerfile   
    ports:
      - "3040:3040"  

